# Generated by Django 5.1.5 on 2025-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad və Soyad')),
                ('email', models.EmailField(max_length=255, verbose_name='E-poçt')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə tarixi')),
            ],
            options={
                'verbose_name': 'Əlaqə mesajı',
                'verbose_name_plural': 'Əlaqə mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
