# Generated by Django 3.2 on 2021-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haqqimizda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sual')),
                ('answer', models.CharField(blank=True, max_length=256, null=True, verbose_name='Cavab')),
            ],
        ),
    ]
