# Generated by Django 3.2 on 2021-04-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haqqimizda', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cavab'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sual'),
        ),
    ]
