# Generated by Django 3.2 on 2021-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haqqimizda', '0006_partnyorlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hastag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tag')),
            ],
        ),
    ]
