# Generated by Django 3.2 on 2021-05-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haqqimizda', '0007_hastag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hastag',
            new_name='Hashtag',
        ),
    ]
