# Generated by Django 5.1.5 on 2025-02-07 12:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haqqimizda', '0008_rename_hastag_hashtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqımızda', 'verbose_name_plural': 'Haqqımızda'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Tez-tez verilən sual', 'verbose_name_plural': 'Tez-tez verilən suallar'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Qalereya', 'verbose_name_plural': 'Qalereya'},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Haştaq', 'verbose_name_plural': 'Haştaqlar'},
        ),
        migrations.AlterModelOptions(
            name='partnyorlar',
            options={'verbose_name': 'Partnyor', 'verbose_name_plural': 'Partnyorlar'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqımızda ətraflı məlumat'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Qalereya şəkli'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Haştaq'),
        ),
        migrations.AlterField(
            model_name='partnyorlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Partnyor loqosu'),
        ),
    ]
