# Generated by Django 3.2 on 2021-05-22 16:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yenilikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Proyektin Adı')),
                ('ikon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqında Ətraflı Məlumat')),
            ],
        ),
    ]
