# Generated by Django 5.1.5 on 2025-02-07 12:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yenilikler', '0002_alter_yenilikler_ikon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yenilikler',
            options={'verbose_name': 'Yenilik', 'verbose_name_plural': 'Yeniliklər'},
        ),
        migrations.AlterField(
            model_name='yenilikler',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Yeniliyin ətraflı məlumatı'),
        ),
        migrations.AlterField(
            model_name='yenilikler',
            name='ikon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='yenilikler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Yeniliyin şəkli'),
        ),
        migrations.AlterField(
            model_name='yenilikler',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Yeniliyin adı'),
        ),
    ]
