# Generated by Django 3.2 on 2021-04-24 10:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xidmetler',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqında Ətraflı Məlumat'),
        ),
        migrations.AddField(
            model_name='xidmetler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
    ]
