# Generated by Django 3.2 on 2021-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0002_auto_20210424_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='xidmetler',
            name='iconimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
    ]
