# Generated by Django 3.2 on 2021-05-22 08:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0004_alter_xidmetler_iconimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='XidmetlerAltKateqoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Xidmet adı')),
                ('iconimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqında Ətraflı Məlumat')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='xidmetler.xidmetler', verbose_name='Kateqoriya')),
            ],
        ),
    ]
