# Generated by Django 3.2 on 2021-05-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0005_xidmetleraltkateqoriya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekiller', to='xidmetler.xidmetler')),
            ],
        ),
    ]
