# Generated by Django 3.2 on 2021-05-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0006_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='project',
            new_name='xidmet',
        ),
    ]
