# Generated by Django 5.1.5 on 2025-02-07 12:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0007_rename_project_images_xidmet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Xidmət Şəkli', 'verbose_name_plural': 'Xidmət Şəkilləri'},
        ),
        migrations.AlterModelOptions(
            name='xidmetler',
            options={'verbose_name': 'Xidmət', 'verbose_name_plural': 'Xidmətlər'},
        ),
        migrations.AlterModelOptions(
            name='xidmetleraltkateqoriya',
            options={'verbose_name': 'Xidmət Alt Kateqoriya', 'verbose_name_plural': 'Xidmət Alt Kateqoriyalar'},
        ),
        migrations.AlterField(
            model_name='images',
            name='xidmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekiller', to='xidmetler.xidmetler', verbose_name='Xidmət'),
        ),
        migrations.AlterField(
            model_name='xidmetler',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqında ətraflı məlumat'),
        ),
        migrations.AlterField(
            model_name='xidmetler',
            name='iconimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='xidmetler',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Xidmət adı'),
        ),
        migrations.AlterField(
            model_name='xidmetleraltkateqoriya',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqında ətraflı məlumat'),
        ),
        migrations.AlterField(
            model_name='xidmetleraltkateqoriya',
            name='iconimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='xidmetleraltkateqoriya',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Xidmət adı'),
        ),
    ]
