# Generated by Django 5.1.5 on 2025-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0008_alter_images_options_alter_xidmetler_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xidmetler',
            name='short_description',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
