# Generated by Django 5.1.5 on 2025-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0009_xidmetler_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='xidmetler',
            name='icon1',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xidmetler',
            name='icon2',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
