# Generated by Django 5.1.5 on 2025-02-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0010_xidmetler_icon1_xidmetler_icon2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xidmetleraltkateqoriya',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='xidmetler.xidmetler', verbose_name='Kateqoriya'),
        ),
    ]
