# Generated by Django 5.1.5 on 2025-02-26 07:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0011_alter_xidmetleraltkateqoriya_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorporativXidmetler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Xidmət adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('short_description', models.CharField(max_length=512)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqında ətraflı məlumat')),
                ('icon1', models.FileField(upload_to='')),
                ('icon2', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Korporativ Xidmət',
                'verbose_name_plural': 'Korporativ Xidmətlər',
            },
        ),
        migrations.RemoveField(
            model_name='xidmetler',
            name='iconimage',
        ),
        migrations.RemoveField(
            model_name='xidmetleraltkateqoriya',
            name='iconimage',
        ),
        migrations.CreateModel(
            name='KorporativImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('xidmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekiller', to='xidmetler.korporativxidmetler', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Xidmət Şəkli',
                'verbose_name_plural': 'Xidmət Şəkilləri',
            },
        ),
    ]
