# Generated by Django 3.2 on 2021-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_kateqoriya_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='portfolio.Category', verbose_name='Kateqoriya'),
        ),
    ]
