# Generated by Django 3.2 on 2021-04-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='projects', to='portfolio.Category', verbose_name='Kateqoriya'),
        ),
    ]
