# Generated by Django 3.2 on 2021-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler', '0005_xidmetleraltkateqoriya'),
        ('portfolio', '0005_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='portfolios', to='xidmetler.Xidmetler', verbose_name='Kateqoriya'),
        ),
    ]
