# Generated by Django 5.1.5 on 2025-02-07 12:50

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_images_project'),
        ('xidmetler', '0009_xidmetler_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Proyekt Şəkli', 'verbose_name_plural': 'Proyekt Şəkilləri'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyekt', 'verbose_name_plural': 'Proyektlər'},
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Proyekt şəkli'),
        ),
        migrations.AlterField(
            model_name='images',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekiller', to='portfolio.project', verbose_name='Proyekt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='portfolios', to='xidmetler.xidmetler', verbose_name='Xidmət kateqoriyası'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Proyekt haqqında ətraflı məlumat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Proyekt şəkli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Proyektin adı'),
        ),
    ]
