# Generated by Django 5.1.5 on 2025-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qalereya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Qalereya', 'verbose_name_plural': 'Qalereya şəkilləri'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Qalereya şəkli'),
        ),
    ]
